@startuml reworked-request-service-class

hide empty attributes
hide empty methods

abstract class AbstractHotelService <<singleton>> {
  - <<readonly>> roomService: AbstractRoomService

  # __construct( roomService: AbstractRoomService )
  + getRoomService(): AbstractRoomService
  + list( args: array ) : HotelEntity[]
}

class UnoptimizedHotelService extends AbstractHotelService {
  # computeDistance( latFrom: float, lngFrom: float, latTo: float, lngTo: float ) : float
  # convertEntityFromArray( data: array, args: array ) : HotelEntity
  # getDB() : PDO
  # getCheapestRoom( hotel: HotelEntity, args: array ) : RoomEntity
  # getMeta( userId: int, key: string ) : ?string
  # getMetas( hotel: HotelEntity ) : array
  # getReviews( hotel: HotelEntity ) : array
}

class OneRequestHotelService extends AbstractHotelService {
  # convertEntityFromArray( args: array ) : HotelEntity
  # getDB() : PDO
  # buildQuery( args: array ) : PDOStatement
}

class ReworkedHotelService extends OneRequestHotelService {

}
@enduml