@startuml

class Database <<singleton>> {
  - <<readonly>> PDO pdo
  - {static} Database instance
  - __construct()
  + {static} get() : PDO
}

note right of Database : La méthode get() et la propriété instance sont statiques

@enduml